spring.application.name=techforge
spring.datasource.url=jdbc:mysql://localhost:3306/techforge?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Duccanh1901
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
